# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b64279039a6d5304ca747e08ab12ba6f6744bcf9811957221571dcd1e71345794bca991edf93f22beb5f6222ee8f24db9732c9ab09f7c911ec5a68203c01497e

test:
  secret_key_base: 2264d1c9879f4cb1672ef0d0f7ab9d206a621f5acfa0a1ed03729f6a984e100041eaf1ff44853ee3dfe1deec89e6fadcca7b06be105d08a6edb1fae9df63ab6d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
